# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: "America/Sao_Paulo"

# jekyll-seo-tag settings
title: Diogo Izele # the main title
tagline: Software Developer | Full-Stack | Mobile Specialist (React Native) # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  A blog about tech, mobile development, and personal growth.

# Fill in the protocol & hostname for your site.
url: "https://blog.diogoizele.com"

github:
  username: diogoizele # change to your GitHub username

twitter:
  username: diogoizele # change to your Twitter username

social:
  name: Diogo Izele # the full name for the author
  email: dev@diogoizele.com # your email address
  links:
    - https://github.com/diogoizele # your GitHub homepage
    - https://www.linkedin.com/in/diogoizele # your LinkedIn profile (if you have)
    # Add more social links if needed, for example Instagram or Medium

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: goatcounter

# Prefer color scheme setting.
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar.jpeg # link to your avatar image (local or URL)

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: /assets/img/social-preview.jpg # link to your preview image

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus # Change to the comment system provider you prefer, like Disqus, Utterances, or Giscus.
  giscus:
    repo: diogoizele/diogoizele.com # your GitHub repo for Giscus integration
    repo_id: # your Giscus repo ID
    category: General # category in Giscus (default: "General")
    category_id: # category ID for the repo

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: false
    env: production

# PWA settings
pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache

paginate: 10 # number of posts per page

# The base URL of your site
baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
